export const GROUP_TEAMS = {
  A: ['Mexico', 'South Africa', 'South Korea', 'Czechia'],
  B: ['Canada', 'Switzerland', 'Qatar', 'Bosnia-Herzegovina'],
  C: ['Brazil', 'Morocco', 'Scotland', 'Haiti'],
  D: ['USA', 'Paraguay', 'Australia', 'Turkiye'],
  E: ['Germany', 'Ecuador', 'Ivory Coast', 'Curacao'],
  F: ['Netherlands', 'Japan', 'Sweden', 'Tunisia'],
  G: ['Belgium', 'Egypt', 'Iran', 'New Zealand'],
  H: ['Spain', 'Uruguay', 'Saudi Arabia', 'Cape Verde'],
  I: ['France', 'Senegal', 'Iraq', 'Norway'],
  J: ['Argentina', 'Austria', 'Algeria', 'Jordan'],
  K: ['Portugal', 'DR Congo', 'Uzbekistan', 'Colombia'],
  L: ['England', 'Croatia', 'Ghana', 'Panama'],
}

export const GROUPS = Object.keys(GROUP_TEAMS)

export const ALL_TEAMS = [...new Set(Object.values(GROUP_TEAMS).flat())].sort()

export const TEAM_FLAG = {
  Algeria:            '🇩🇿',
  Argentina:          '🇦🇷',
  Australia:          '🇦🇺',
  Austria:            '🇦🇹',
  Belgium:            '🇧🇪',
  'Bosnia-Herzegovina':'🇧🇦',
  Brazil:             '🇧🇷',
  Canada:             '🇨🇦',
  'Cape Verde':       '🇨🇻',
  Colombia:           '🇨🇴',
  Croatia:            '🇭🇷',
  Curacao:            '🇨🇼',
  Czechia:            '🇨🇿',
  'DR Congo':         '🇨🇩',
  Ecuador:            '🇪🇨',
  Egypt:              '🇪🇬',
  England:            '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  France:             '🇫🇷',
  Germany:            '🇩🇪',
  Ghana:              '🇬🇭',
  Haiti:              '🇭🇹',
  Iran:               '🇮🇷',
  Iraq:               '🇮🇶',
  'Ivory Coast':      '🇨🇮',
  Japan:              '🇯🇵',
  Jordan:             '🇯🇴',
  Mexico:             '🇲🇽',
  Morocco:            '🇲🇦',
  Netherlands:        '🇳🇱',
  'New Zealand':      '🇳🇿',
  Norway:             '🇳🇴',
  Panama:             '🇵🇦',
  Paraguay:           '🇵🇾',
  Portugal:           '🇵🇹',
  Qatar:              '🇶🇦',
  'Saudi Arabia':     '🇸🇦',
  Scotland:           '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  Senegal:            '🇸🇳',
  'South Africa':     '🇿🇦',
  'South Korea':      '🇰🇷',
  Spain:              '🇪🇸',
  Sweden:             '🇸🇪',
  Switzerland:        '🇨🇭',
  Tunisia:            '🇹🇳',
  Turkiye:            '🇹🇷',
  USA:                '🇺🇸',
  Uruguay:            '🇺🇾',
  Uzbekistan:         '🇺🇿',
}

// FIFA World Rankings as of April 1, 2026
export const FIFA_RANKING = {
  France:               1,
  Spain:                2,
  Argentina:            3,
  England:              4,
  Portugal:             5,
  Brazil:               6,
  Netherlands:          7,
  Morocco:              8,
  Belgium:              9,
  Germany:              10,
  Croatia:              11,
  Colombia:             13,
  Senegal:              14,
  Mexico:               15,
  USA:                  16,
  Uruguay:              17,
  Japan:                18,
  Switzerland:          19,
  Iran:                 21,
  Turkiye:              22,
  Ecuador:              23,
  Austria:              24,
  'South Korea':        25,
  Australia:            27,
  Algeria:              28,
  Egypt:                29,
  Norway:               31,
  Panama:               33,
  'Ivory Coast':        34,
  Sweden:               38,
  Paraguay:             40,
  Czechia:              41,
  Scotland:             43,
  Tunisia:              44,
  'DR Congo':           46,
  Uzbekistan:           50,
  Qatar:                55,
  Iraq:                 57,
  'South Africa':       60,
  'Saudi Arabia':       61,
  Jordan:               63,
  'Bosnia-Herzegovina': 65,
  'Cape Verde':         69,
  Ghana:                74,
  'New Zealand':        85,
  Haiti:                83,
  Canada:               30,
  Curacao:              82,
}

export const PROPS = [
  { key: 'Winner',               label: 'Tournament Winner',   type: 'team',   points: 10, hint: 'Which team lifts the trophy?' },
  { key: 'Runner-up',            label: 'Runner-Up',           type: 'team',   points: 6,  hint: 'Finalist who falls short' },
  { key: 'Golden Boot',          label: 'Golden Boot',         type: 'player', points: 5,  hint: 'Tournament top scorer' },
  { key: 'Golden Glove',         label: 'Golden Glove',        type: 'player', points: 4,  hint: 'Best goalkeeper' },
  { key: 'Player of Tournament', label: 'Best Player',         type: 'player', points: 5,  hint: 'Tournament MVP' },
  { key: 'Young Player',         label: 'Best Young Player',   type: 'player', points: 4,  hint: 'U-21 standout' },
  { key: 'Biggest Surprise',     label: 'Biggest Surprise',    type: 'team',   points: 4,  hint: 'Most overachieving team' },
  { key: 'Biggest Flop',         label: 'Biggest Flop',        type: 'team',   points: 4,  hint: 'Most disappointing team' },
  { key: 'Breakout Player',      label: 'Breakout Player',     type: 'player', points: 4,  hint: 'Emerging star of the tournament' },
  { key: '# of Set Piece Goals', label: 'Set Piece Goals',     type: 'number', points: 3,  hint: 'Total goals from corners, free kicks & penalties' },
]
